const orders = [
    {
      id: 1,
      pickupAddress: "123 Main St",
      dropAddress: "456 Elm St",
      date: "2024-06-30",
      distance: "10 km",
      status: "complete",
      price: 150,
    },
    {
      id: 2,
      pickupAddress: "789 Oak Ave",
      dropAddress: "101 Pine Blvd",
      date: "2024-07-01",
      distance: "8 km",
      status: "complete",
      price: 120,
    },
    {
      id: 3,
      pickupAddress: "222 Maple Dr",
      dropAddress: "333 Cedar Ln",
      date: "2024-07-02",
      distance: "15 km",
      status: "cancel",
      price: 180,
    },
    {
      id: 4,
      pickupAddress: "444 Birch Rd",
      dropAddress: "555 Willow Ct",
      date: "2024-07-03",
      distance: "12 km",
      status: "complete",
      price: 160,
    },
    {
      id: 5,
      pickupAddress: "666 Oak St",
      dropAddress: "777 Pine St",
      date: "2024-07-04",
      distance: "7 km",
      status: "cancel",
      price: 110,
    },
    {
      id: 6,
      pickupAddress: "888 Maple Ave",
      dropAddress: "999 Cedar Blvd",
      date: "2024-07-05",
      distance: "20 km",
      status: "complete",
      price: 200,
    },
    {
      id: 7,
      pickupAddress: "111 Birch Dr",
      dropAddress: "222 Willow Ln",
      date: "2024-07-06",
      distance: "18 km",
      status: "complete",
      price: 190,
    },
    {
      id: 8,
      pickupAddress: "333 Oak Rd",
      dropAddress: "444 Pine Ct",
      date: "2024-07-07",
      distance: "9 km",
      status: "cancel",
      price: 130,
    },
    {
      id: 9,
      pickupAddress: "555 Maple St",
      dropAddress: "666 Cedar St",
      date: "2024-07-08",
      distance: "14 km",
      status: "complete",
      price: 170,
    },
    {
      id: 10,
      pickupAddress: "777 Birch Ave",
      dropAddress: "888 Willow Blvd",
      date: "2024-07-09",
      distance: "11 km",
      status: "complete",
      price: 140,
    },
  ];
  
  export default orders;
  